[project]
name = "procose"
version = "0.1.0"
description = "Syntactic sugar for python subprocesses"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rich>=13.0.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/procose"]

[project.scripts]
procose = "procose.cli:main"
testapp = "procose.testapp:main"
