name: Setup Nix with Caching
description: Install Nix and configure caching for optimal performance
runs:
  using: composite
  steps:
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v30

    - name: Restore and save Nix store
      uses: nix-community/cache-nix-action@v6
      with:
        primary-key: nix-store-${{ runner.os }}-${{ hashFiles('**/flake.lock') }}
        restore-prefixes-first-match: nix-store-${{ runner.os }}
        # Collect garbage until store is at most 8GB before saving cache  
        gc-max-store-size: 8G 