name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v13

      - name: Cache Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: ${{ runner.os }}-nix-${{ hashFiles('flake.lock', 'flake.nix', 'pyproject.toml', 'src/**', 'tests/**', 'nix/**') }}
          restore-prefixes-first-match: ${{ runner.os }}-nix-
          paths: |
            ~/.cache/nix
            /nix/store

      - name: Run full checklist on main branch
        if: github.ref == 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/')
        run: nix run .#checklist-full

      - name: Run release checklist on tag
        if: startsWith(github.ref, 'refs/tags/')
        run: nix run .#checklist-release 