name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Hello on main branch push
        if: github.ref == 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/')
        run: echo "hello world"

      - name: Hello on tag push
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "hello ${{ github.ref_name }}" 