name: Test

on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'nix/**'
      - '.github/**'
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Run fast checks
        run: nix run .#checklist-fast -- -v

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Run full test suite
        if: github.ref == 'refs/heads/main'
        run: nix run .#checklist-full -- -v

      - name: Run release checklist
        if: startsWith(github.ref, 'refs/tags/')
        run: nix run .#checklist-release -- -v

  # Wheel testing is now handled in release.yml workflow
  # which builds portable wheels using CI-based approach 